<main>
    <div class="ui container">
        <div class="ui grid">
            <div class="sixteen wide column">
                <div class="col page-title">
                    <h2 class="ui header">
                        Custom fields
                        <a href="/admin/settings/custom_fields/" class="ui primary basic button right floated item">
                            <i class="arrow left icon"></i> Group fields
                        </a>
                    </h2>
                </div>
            </div>
        </div>
        <div class="ui grid">
            <div class="sixteen wide column">
                <div class="setting-tabs">
                    <?php echo Component::get('settings/tabs') ?>
                </div>
            </div>
        </div>

        <div class="ui grid">
            <div class="twelve wide column">
                <?php if (!empty($fieldList)): ?>
                    <form id="updateFieldsGroup">
                        <input type="hidden" name="group_id" value="<?php echo $group->id ?>">
                        <div id="containerFields" class="ui styled fluid accordion">
                            <?php foreach ($fieldList as $field) {
                                echo Component::get('custom_fields/components/item_field', [
                                        'field' => $field
                                ]);
                            } ?>
                        </div>
                    </form>
                    <br>
                    <button class="ui basic button" onclick="customField.addField(<?php echo $group->id ?>)">
                        <i class="icon plus"></i>
                        Add Field
                    </button>
                <?php else: ?>
                    <form id="updateFieldsGroup">
                        <input type="hidden" name="group_id" value="<?php echo $group->id ?>">
                        <div id="containerFields" class="ui styled fluid accordion"></div>
                    </form>
                    <br>
                    <div class="row">
                        <div class="col">
                            <div class="empty-list-text">
                                <div class="ui basic segment">
                                    <p>Empty field list</p>
                                    <button class="ui basic button" onclick="customField.addField(<?php echo $group->id ?>)">
                                        <i class="icon plus"></i>
                                        Add Field
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <div class="four wide column">
                <div class="ui segments">
                    <div class="ui blue segment">
                        <h4>Settings</h4>
                    </div>
                    <div class="ui secondary segment">
                        <p>Update this fields</p>
                        <button type="submit" class="ui primary button" onclick="customField.updateFieldsGroup(this)">
                            Update
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>