<main>
    <div class="ui container">
        <div class="ui grid">
            <div class="sixteen wide column">
                <div class="col page-title">
                    <h2 class="ui header">
                        <?= $page->title ?>
                        <div class="sub header grey">
                            <?php echo $baseUrl . '/page/' . $page->segment ?>
                        </div>
                    </h2>
                </div>
            </div>
        </div>
        <div class="ui grid">
            <div class="twelve wide column">
                <div class="ui secondary menu">
                    <a class="item active" data-tab="content">Content</a>
                    <?php if (!empty($customFields)): ?>
                    <a class="item" data-tab="custom_fields">Custom fields</a>
                    <?php endif; ?>
                </div>
                <div class="ui bottom attached tab active" data-tab="content">
                    <form id="formPage" class="ui form">
                        <input type="hidden" name="page_id" id="formPageId" value="<?= $page->id ?>" />
                        <div class="field">
                            <label><?php __('pages.edit.label_title') ?></label>
                            <input type="text" name="title" class="form-control" id="formTitle" value="<?= $page->title ?>" placeholder="<?php __('page.edit.placeholder_title') ?>">
                        </div>
                        <div class="field">
                            <label><?php __('pages.edit.label_content') ?></label>
                            <textarea name="content" id="redactor"><?= $page->content ?></textarea>
                        </div>
                    </form>
                </div>
                <?php if (!empty($customFields)): ?>
                <div class="ui bottom attached tab" data-tab="custom_fields">
                    <div class="ui styled fluid accordion">
                        <form id="customFieldsForm" class="ui form">
                        <?php foreach ($customFields as $group): ?>
                            <div class="title">
                                <i class="dropdown icon"></i>
                                <?php echo $group['group']->title ?>
                            </div>
                            <div class="content">
                                <?php if (isset($group['fields'])) {
                                    foreach ($group['fields'] as $field) {
                                        echo $field->html;
                                    }
                                } else {
                                    echo '<p>There are no fields in this group.</p>';
                                } ?>
                            </div>
                            <?php endforeach; ?>
                        </form>
                    </div>
                </div>
                <?php endif; ?>
            </div>
            <div class="four wide column">
                <div class="ui segments">
                    <div class="ui blue segment">
                        <h4><?php __('pages.edit.update_segment_heading') ?></h4>
                    </div>
                    <div class="ui form segment">
                        <div class="field">
                            <label><?php __('pages.edit.label_status') ?></label>
                            <select id="status" class="ui search dropdown">
                                <option value="publish"<?php if ('publish' == $page->status) echo ' selected'; ?>>Опубликовано</option>
                                <option value="draft"<?php if ('draft' == $page->status) echo ' selected'; ?>>В корзине</option>
                            </select>
                        </div>
                    </div>
                    <div class="ui secondary segment">
                        <p><?php __('pages.edit.description_form_button') ?></p>
                        <button type="submit" class="ui primary button" onclick="page.update(this)">
                            <?php __('pages.edit.form_button') ?>
                        </button>
                    </div>
                </div>

                <div class="ui segments">
                    <div class="ui blue segment">
                        <h4><?php __('pages.edit.setting_segment.heading') ?></h4>
                    </div>
                    <div class="ui form segment">
                        <div class="field">
                            <label>Layout</label>
                            <select id="layout" class="ui search dropdown">
                                <option value="main">Main</option>
                                <?php foreach ($layouts as $key => $layout): ?>
                                    <option value="<?php echo $key ?>"<?php if ($key == $page->layout) echo ' selected'; ?>>
                                        <?php echo $layout ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="ui form segment">
                        <div class="field">
                            <label><?php __('pages.edit.setting_segment.label_type') ?></label>
                            <select id="type" class="ui search dropdown">
                                <option value="page">Basic</option>
                                <?php foreach ($pageTypes as $key => $type): ?>
                                    <option value="<?php echo $key ?>"<?php if ($key == $page->type) echo ' selected'; ?>>
                                        <?php echo $type ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>