<main>
    <div class="ui container">
        <div class="ui grid">
            <div class="sixteen wide column">
                <div class="col page-title">
                    <h2 class="ui header">
                        <?php __('settings.menus.heading') ?>
                    </h2>
                </div>
            </div>
        </div>
        <div class="ui grid">
            <div class="sixteen wide column">
                <div class="setting-tabs">
                    <?php echo Component::get('settings/tabs') ?>
                </div>
            </div>
        </div>

        <div class="ui grid">
            <div class="four wide column">
                <?php if(!empty($menus)): ?>
                    <div class="ui vertical pointing menu">
                        <?php foreach($menus as $menu): ?>
                            <a class="item<?php if ($menuId == $menu->id) echo ' active'; ?>" href="?menu_id=<?php echo $menu->id ?>">
                                <?php echo $menu->name ?>
                            </a>
                        <?php endforeach; ?>
                    </div>
                <?php else: ?>
                    <div class="empty-items">
                        <p><?php __('settings.menus.not_have_menu') ?></p>
                    </div>
                <?php endif; ?>
                <a href="javascript:void(0)" class="ui primary button btn-create-menu">
                    <?php __('settings.menus.create_menu_button') ?>
                </a>
            </div>
            <div class="twelve wide column">
                <?php if ($menuId !== null): ?>
                    <input type="hidden" id="sortMenuId" value="<?php echo $menuId ?>" />
                    <ol id="listItems" class="edit-menu">
                        <?php foreach($editMenu as $item) {
                            echo \Component::get('settings/menu_item', [
                                'item' => $item
                            ]);
                        } ?>
                    </ol>
                    <button class="ui basic button" onclick="menu.addItem(<?php echo $menuId ?>)">
                        <i class="plus icon"></i>
                        <?php __('settings.menus.create_menu_item_button') ?>
                    </button>
                <?php endif; ?>
            </div>
        </div>
    </div>
</main>

<div id="addMenu" class="ui dimmer modals page transition">
    <div class="ui standard test modal transition hidden">
        <div class="ui mini test modal transition">
            <div class="header">
                <?php __('settings.menus.modal_form.heading') ?>
            </div>
            <div class="content">
                <div class="ui form">
                    <div class="required field">
                        <label><?php __('settings.menus.modal_form.label_name') ?></label>
                        <input type="text" placeholder="<?php __('settings.menus.modal_form.placeholder_name') ?>" id="menuName">
                    </div>
                </div>
            </div>
            <div class="actions">
                <div class="ui negative button">
                    <?php __('settings.menus.modal_form.cancel_button') ?>
                </div>
                <div class="ui positive right labeled icon button" onclick="menu.add();">
                    <?php __('settings.menus.modal_form.create_button') ?>
                    <i class="checkmark icon"></i>
                </div>
            </div>
        </div>
    </div>
</div>