<main>
    <div class="ui container">
        <div class="row">
            <div class="col page-title">
                <h2 class="ui header">
                    <?php __('posts.list.title') ?>
                    <a href="/admin/posts/create/" class="ui primary button right floated item">
                        <?php __('posts.list.create_button') ?>
                    </a>
                </h2>
            </div>
        </div>

        <table class="ui very basic table">
            <thead>
            <tr>
                <th>#</th>
                <th><?php __('posts.list.table_title') ?></th>
                <th><?php __('posts.list.table_date') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($posts as $post): ?>
                <tr>
                    <th scope="row">
                        <?= $post->id ?>
                    </th>
                    <td>
                        <a href="/admin/posts/edit/<?= $post->id ?>">
                            <?= $post->title ?>
                        </a>
                    </td>
                    <td>
                        <?= $post->date ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>