<main>
    <div class="ui container">
        <div class="row">
            <div class="col page-title">
                <h2 class="ui header">
                    <?php __('pages.list.title') ?>
                    <a href="/admin/pages/create/" class="ui primary button right floated item">
                        <?php __('pages.list.create_button') ?>
                    </a>
                </h2>
            </div>
        </div>

        <table class="ui very basic table">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php __('pages.list.table_title') ?></th>
                    <th><?php __('pages.list.table_date') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php
            /** @var \Flexi\Cms\Admin\Model\Page $page */
            foreach($pages as $page): ?>
                <tr>
                    <th scope="row">
                        <?= $page->id ?>
                    </th>
                    <td>
                        <a href="/admin/pages/edit/<?= $page->id ?>">
                            <?= $page->title ?>
                        </a>
                    </td>
                    <td>
                        <?= $page->date ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>